### ISSUE TITLE
Error occurred while downloading plugins

### ISSUE THREAD

**Issue by ItsGenesix** [sepluginloader/PluginLoader#49]
unsure what log im supposed to put in here for assistance, but i found this in the loader log;

2023-05-31T01:05:33.5857905Z Downloading https://raw.githubusercontent.com/sepluginloader/PluginHub/main/plugins.sha1
2023-05-31T01:05:38.6111173Z Error while downloading whitelist hash: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at avaness.PluginLoader.Network.GitHub.GetStream(Uri uri)
   at avaness.PluginLoader.Network.GitHub.DownloadFile(String name, String commit, String path)
   at avaness.PluginLoader.PluginList.TryDownloadWhitelistHash(String& hash)
2023-05-31T01:05:38.6120985Z No whitelist cache exists
2023-05-31T01:05:38.6120985Z WARNING: No plugins in the plugin list. Plugin list will contain local plugins only.
2023-05-31T01:05:38.6420754Z Found 0 plugins
2023-05-31T01:05:38.6570884Z Enabled plugins: None
2023-05-31T01:05:38.6580881Z Downloading user statistics
2023-05-31T01:05:38.6810624Z Patching
2023-05-31T01:05:39.4628095Z Instantiating plugins
2023-05-31T01:05:39.4628095Z Finished startup. Took 6368ms
2023-05-31T01:05:43.6344600Z Loading 0 plugins
2023-05-31T01:05:43.6854434Z Initializing 0 plugins

**Comment by austinvaness** [comment]
In config.xml there is a line that says `<AllowIPv6>true</AllowIPv6>` change true to false. If that works, there is a similar setting in launcher.xml

**Comment by steinblitz** [comment]
this worked for me tyty
