### ISSUE TITLE
loader keeps crashing after update where does the Loader store everything at to try to do a clean wipe

### ISSUE THREAD

**Issue by Soldierofthelam** [sepluginloader/PluginLoader#50]

**Comment by protocolist** [comment]
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Cannot create instance of 'avaness.PluginLoader.Main': System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingFieldException: Field not found: 'ResultData.Success'.

   at avaness.PluginLoader.SteamAPI.Update(IEnumerable`1 ids)

   at avaness.PluginLoader.PluginList..ctor(String mainDirectory, PluginConfig config)

   at avaness.PluginLoader.Main..ctor()

   --- End of inner exception stack trace ---

   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)

   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)

   at System.Activator.CreateInstance(Type type, Boolean nonPublic)

   at System.Activator.CreateInstance(Type type)

   at VRage.Plugins.MyPlugins.LoadPlugins(List`1 assemblies)



   at VRage.Plugins.MyPlugins.LoadPlugins(List`1 assemblies)

   at VRage.Plugins.MyPlugins.Load()

   at Sandbox.MySandboxGame..ctor(String[] commandlineArgs, IntPtr windowHandle)

   at SpaceEngineers.Game.SpaceEngineersGame..ctor(String[] commandlineArgs)

   at SpaceEngineers.MyProgram.Main(String[] args)

   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)

   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)


---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by protocolist** [comment]
I also have this issue, regardless of whether using existing Plugin directory.

**Comment by Soldierofthelam** [comment]
> I also have this issue, regardless of whether using existing Plugin directory.

Keen just had an update it will take to for them to update the loader I just want to clear the files though for a clean .exe when the loader gets updated

**Comment by protocolist** [comment]
> > I also have this issue, regardless of whether using existing Plugin directory.
> 
> Keen just had an update, It will take some time for them to update the loader I just want to clear the files though for a clean .exe when the loader gets updated

Delete/rename/move the directory "Plugins" in Bin64

**Comment by austinvaness** [comment]
Fixed in loader v1.11.5. You dont have to do anything to your file system, just let the launcher update the loader.
