### ISSUE TITLE
Space engineers throws error (Chat Translator Plugin) (log) (WIP New Plugin)

### ISSUE THREAD

**Issue by NingyMD** [sepluginloader/PluginLoader#67]
I have been *trying* to make something for plugin loader recently but I keep getting error after error and I cant seem to figure it out.
The plugin is meant to translate chat messages to whatever language your games language settings are at.

This is the part of the error that I think I should be focused on.
```
2024-08-09 19:17:14.141 - Thread:   1 ->  [PluginLoader] [Error] Failed to load C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64\Plugins\Local\ChatTranslatorPlugin.dll because of an exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at avaness.PluginLoader.PluginInstance.TryGet(PluginData data, PluginInstance& instance)
Exception details: 
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

The attached image is the file structure in Visual Studio Code.
![image](https://github.com/user-attachments/assets/062c1cfb-675f-47f7-a24f-e7c224b627b9)
[SpaceEngineers_20240809_191708315.log](https://github.com/user-attachments/files/16568229/SpaceEngineers_20240809_191708315.log)

Here is the project Github    https://github.com/NingyMD/SE-ChatTranslatorPlugin/tree/main

**Comment by austinvaness** [comment]
Space Engineers is a .net framework application, you must target .net framework 4.8 and use c# version 7.3 at most.
