### ISSUE TITLE
Failed to download plugin list

### ISSUE THREAD

**Issue by Ornifd** [sepluginloader/PluginLoader#71]
I have an error that say " an error occurred while downloading plugin list"

 And my log file :

2024-11-03 15:57:29.7301 [INFO] (1) Saving config
2024-11-03 15:57:29.8261 [INFO] (1) Downloading https://raw.githubusercontent.com/sepluginloader/PluginHub/main/plugins.sha1
2024-11-03 15:57:55.8929 [ERROR] (1) Error while downloading whitelist hash: System.Net.WebException: Le délai d'attente de l'opération a expiré .
   at System.Net.HttpWebRequest.GetResponse()
   at avaness.PluginLoader.Network.GitHub.GetStream(Uri uri)
   at avaness.PluginLoader.Network.GitHub.DownloadFile(String name, String commit, String path)
   at avaness.PluginLoader.PluginList.TryDownloadWhitelistHash(String& hash)
2024-11-03 15:57:55.8929 [INFO] (1) No whitelist cache exists
2024-11-03 15:57:55.8929 [WARN] (1) No plugins in the plugin list. Plugin list will contain local plugins only.
2024-11-03 15:57:56.0036 [INFO] (1) Found 0 plugins
2024-11-03 15:57:56.0483 [INFO] (1) Enabled plugins: None
2024-11-03 15:57:56.0483 [INFO] (17) Downloading plugin statistics anonymously...
2024-11-03 15:57:56.0870 [INFO] (1) Patching
2024-11-03 15:57:56.5102 [INFO] (1) Instantiating plugins
2024-11-03 15:57:56.5102 [INFO] (1) Finished startup. Took 27136ms
2024-11-03 15:57:58.3377 [INFO] (1) Loading 0 plugins
2024-11-03 15:57:58.3685 [INFO] (1) Initializing 0 plugins

Any idea on how to solve that ?

**Comment by Ornifd** [comment]
Well... I don't know how, but I solved it.

**Comment by austinvaness** [comment]
Sometimes this can be caused by a bad ipv6 internet connection. Maybe that's what's happening?

**Comment by Platysum** [comment]
Maybe, but I'm not sure about that. I just uninstaled it and instaled it one more time and this time it worked. It might be due to a bad file instal or something like that.

**Comment by Platysum** [comment]
My other acoount, sorry.
